spring:
  profiles:
    active:
    - dev
---
spring:
  profiles:
    active:
    - dev
  application:
    name: micservicecloud-config-dev
---
spring:
  profiles:
    active:
    - sit
  application:
    name: micservicecloud-config-sit            
