server:
  port: 8203
spring:
  profiles: uat
  application:
    name: micservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-uat.com:7001/eureka/      
    
